binop_separator = "Back"
brace_style = "SameLineWhere"
max_width = 112
color = "Always"
edition = "2021"
fn_single_line = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
hex_literal_case = "Lower"
imports_layout = "HorizontalVertical"
indent_style = "Block"
imports_granularity = "Crate"
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
report_fixme = "Unnumbered"
space_after_colon = true
tab_spaces = 4
trailing_semicolon = false
trailing_comma = "Never"
use_field_init_shorthand = true
where_single_line = true
